### ISSUE TITLE
TypeError: `pad_width` must be of integral type

### ISSUE THREAD

**Issue by ggrrll** [schen59/SRLab#2]
Hi, 

after running  `python3.6 sr_image_example.py` I got:

```
TypeError: `pad_width` must be of integral type.
```

**Comment by schen59** [comment]
It supports python 2.7.x only.

Sent from my iPhone

On Mar 13, 2017, at 10:53 AM, Gianr Lazz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

after running python3.6 sr_image_example.py I got:

TypeError: `pad_width` must be of integral type.

**Comment by ggrrll** [comment]
thanks - I managed indeed to run the examples
